package com.cts.sonarhandson;

public class Add {
    public int add(int a,int b)
    {
        int c;
        c = a+b;
        System.out.println("Adding 2 numbers: "+c);
        return c;
        
    }
    // Generated by Copilot- Start
    public int addThreeNumbers(int a, int b, int c)
    {
        int result;
        result = a + b + c;
        System.out.println("Adding 3 numbers: " + result);
        return result;
    }
    // Generated by Copilot- End
// add a method to verify if a number is even or odd
    // Generated by Copilot- Start
    public boolean isEven(int a)
    {
        boolean result = false;
        if(a%2==0)
        {
            result = true;
        }
        return result;
    }
    // Generated by Copilot- End
}
