package com.cts.sonarhandson;

public class BasicCalculator 
{
	public int add(int a,int b)
	{
		int c;
		c = a+b;
		System.out.println("Adding 2 numbers: "+c);
		return c;
		
	}
	
	// Generated by Copilot- Start
	public int addThreeNumbers(int a, int b, int c)
	{
		int result;
		result = a + b + c;
		System.out.println("Adding 3 numbers: " + result);
		return result;
	}
	// Generated by Copilot- End
	
	public int sub(int a,int b)
	{
		int c;
		c = a-b;
		System.out.println("Substracting 2 numbers: "+c);
		return c;
	}
	
	public int divide(int a, int b) throws Exception
	{
		if (b==0)
		{
			throw new Exception("Denominator cannot be 0.");
		}
		return a/b;
	}
	
	public boolean equalIntegers(int a,int b)
	{
		boolean result = false;
		if(a==b)
		{
			result = true;
		}
		return result;
	}

// Generated by Copilot- Start
	//add a method to verify if a number is even or odd
	public boolean isEven(int a)
	{
		boolean result = false;
		if(a%2==0)
		{
			result = true;
		}
		return result;
	}
	// Generated by Copilot- End
	// Generated by Copilot- Start
//add a method to verify if a number is prime or not
	public boolean isPrime(int number) {
	    if (number <= 1) {
	        return false;
	    }
	    for (int i = 2; i <= Math.sqrt(number); i++) {
	        if (number % i == 0) {
	            return false;
	        }
	    }
	    return true;
	}
	// Generated by Copilot- End
	// Generated by Copilot- Start
	//add a method to verify if a number is composite or not
	public boolean isComposite(int number) {
	    if (number <= 1) {
	        return false;
	    }
	    for (int i = 2; i <= Math.sqrt(number); i++) {
	        if (number % i == 0) {
	            return true;
	        }
	    }
	    return false;
	}
	// Generated by Copilot- End
	// Generated by Copilot- Start
	//add a method to calculate the factorial of a number
	public int factorial(int number) {
	    if (number < 0) {
	        throw new IllegalArgumentException("Number must be non-negative.");
	    }
	    int result = 1;
	    for (int i = 1; i <= number; i++) {
	        result *= i;
	    }
	    return result;
	}
	// Generated by Copilot- End
	// Generated by Copilot- Start
	//add a method to calculate the power of a number
	public double power(double base, int exponent) {
			    return Math.pow(base, exponent);
	}
	// Generated by Copilot- End

		// Generated by Copilot- Start
	public int multiplyThreeNumbers(int a, int b, int c)
	{
		int result;
		result = a * b * c;
		System.out.println("Multiplying 3 numbers: " + result);
		return result;
	}
	// Generated by Copilot- End

	// Generated by Copilot- Start
	public double squareRoot(double number) throws IllegalArgumentException
	{
		if (number < 0) {
			throw new IllegalArgumentException("Cannot calculate square root of negative number.");
		}
		double result = Math.sqrt(number);
		System.out.println("Square root of " + number + ": " + result);
		return result;
	}
	// Generated by Copilot- End

	// Generated by Copilot comments blocks lines added count: 48
}


